# Generated by Django 3.1.2 on 2020-12-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_auto_20201213_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('open', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('archived', models.BooleanField(default=False)),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.level')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person')),
            ],
            options={
                'verbose_name': 'Ballot',
                'verbose_name_plural': 'Ballots',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('A', 'Abstain'), ('L', 'On Leave')], max_length=1)),
                ('comment', models.TextField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.ballot')),
                ('caster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('caster', 'ballot'), name='one_vote_per_ballot'),
        ),
    ]
