# Generated by Django 3.1.2 on 2022-11-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='DeviceType',
        ),
    ]
