# Generated by Django 3.1.2 on 2022-12-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20221201_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='owner',
            new_name='assignee',
        ),
    ]
