# Generated by Django 3.1.2 on 2022-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20221204_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('available', 'Available'), ('broken', 'Broken'), ('discarded', 'Discarded'), ('returned', 'Returned to Customer'), ('stored', 'Stored')], default='allocated', max_length=9),
        ),
    ]
