# Generated by Django 3.1.2 on 2022-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
