# Generated by Django 3.1.2 on 2021-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20210708_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='teams',
            field=models.ManyToManyField(to='people.Team'),
        ),
    ]
