# Generated by Django 3.1.2 on 2021-07-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
