# Generated by Django 3.1.2 on 2021-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20210708_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='teams',
            field=models.ManyToManyField(blank=True, to='people.Team'),
        ),
    ]
