# Generated by Django 3.1.2 on 2021-07-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20210711_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
