# Generated by Django 3.1.2 on 2022-11-14 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20221113_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_query', models.CharField(max_length=100, null=True)),
                ('tz_name', models.CharField(default='Etc/UTC', max_length=30)),
                ('work_begin_time', models.TimeField(default=datetime.time(9, 0))),
                ('work_end_time', models.TimeField(default=datetime.time(18, 0))),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'verbose_name': 'Personal data',
                'verbose_name_plural': 'Personal data',
            },
        ),
    ]
