# Generated by Django 3.1.2 on 2022-11-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='location_query',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
