# Generated by Django 3.1.14 on 2023-12-15 11:50

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    replaces = [('people', '0014_personaldata_avatar'), ('people', '0015_auto_20231215_1143'), ('people', '0016_auto_20231215_1148')]

    dependencies = [
        ('people', '0013_auto_20221114_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='avatar',
            field=models.ImageField(null=True, upload_to=people.models.mangle_filename),
        ),
    ]
