# Generated by Django 3.1.14 on 2024-01-12 09:04

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_personaldata_avatar_squashed_0016_auto_20231215_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=people.models.mangle_filename),
        ),
    ]
