# Generated by Django 3.1.14 on 2023-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_personaldata_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
