# Generated by Django 3.1.14 on 2023-12-15 11:48

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20231215_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='avatar',
            field=models.ImageField(null=True, upload_to=people.models.mangle_filename),
        ),
    ]
