# Generated by Django 3.1.2 on 2020-10-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.IntegerField(choices=[(0, 'None'), (1, 'Touched it while doing unrelated things'), (2, 'Did minor things there'), (3, 'Did major things there'), (4, 'Expert')], default=0)),
                ('interest', models.IntegerField(choices=[(0, 'None'), (1, "I wouldn't mind working in this area"), (2, 'I would like to work in this area'), (3, 'I really want to work in this area'), (4, 'I am obsessed with it!')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.category')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('levels', models.ManyToManyField(to='skills.Measurement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
    ]
