# Generated by Django 3.1.2 on 2020-11-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201101_1346'),
        ('skills', '0002_auto_20201101_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='personassessment',
            unique_together={('date', 'person')},
        ),
    ]
