# Generated by Django 3.1.2 on 2020-12-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_auto_20201123_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='personassessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
