# Generated by Django 3.1.2 on 2021-06-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_project_projectfocusrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectfocusrecord',
            options={'verbose_name': 'Project focus record', 'verbose_name_plural': 'Project focus records'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False, verbose_name='The team is/was working on it'),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default='2021-06-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='DS', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
