# Generated by Django 3.1.2 on 2021-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_auto_20210612_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(verbose_name='Last assessment'),
        ),
        migrations.AddConstraint(
            model_name='projectfocusrecord',
            constraint=models.UniqueConstraint(fields=('project', 'skill'), name='unique_skill_in_project'),
        ),
    ]
