# Generated by Django 3.1.2 on 2021-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_teams'),
        ('skills', '0011_auto_20210613_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(to='people.Team'),
        ),
        migrations.AddField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(to='people.Team'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='skill_name_unique_in_category'),
        ),
    ]
