# Generated by Django 3.1.2 on 2021-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_auto_20210708_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Title'),
        ),
    ]
