# Generated by Django 3.1.2 on 2021-07-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_auto_20210708_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
    ]
