# Generated by Django 3.1.2 on 2021-07-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_auto_20210708_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
