# Generated by Django 3.1.2 on 2021-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20210711_1724'),
        ('skills', '0015_auto_20210709_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(blank=True, to='people.Team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, to='people.Team'),
        ),
    ]
