# Generated by Django 3.1.2 on 2023-12-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20221114_2001'),
        ('skills', '0016_auto_20210711_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.project')),
                ('skills', models.ManyToManyField(blank=True, to='skills.Skill')),
            ],
        ),
    ]

