
# Generated by Django 3.1.2 on 2023-12-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0017_contribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
    ]

