# Generated by Django 3.1.14 on 2024-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_auto_20231207_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='interest',
            field=models.IntegerField(choices=[(0, 'No interest'), (1, 'I would not mind working in this area'), (2, 'I would like to work in this area'), (3, 'I really want to work in this area'), (4, 'This is one of my favourite areas')], default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='knowledge',
            field=models.IntegerField(choices=[(0, 'No knowledge'), (1, 'Touched it while doing unrelated things'), (2, 'Did minor things there'), (3, 'Did major things there'), (4, 'I am expert in this area')], default=0),
        ),
    ]
